# Generated by Django 4.1.13 on 2024-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_mobile_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=models.CharField(max_length=255, null=True, verbose_name='Type'),
        ),
    ]
