# Generated by Django 4.1.13 on 2024-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='producer',
            field=models.CharField(max_length=255, null=True, verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='style',
            field=models.CharField(max_length=255, null=True, verbose_name='Styles'),
        ),
    ]
