# Generated by Django 4.1.13 on 2024-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='books_id',
            field=models.CharField(max_length=255, null=True, verbose_name='bookid'),
        ),
        migrations.AddField(
            model_name='order',
            name='clothes_id',
            field=models.CharField(max_length=255, null=True, verbose_name='clothesid'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobiles_id',
            field=models.CharField(max_length=255, null=True, verbose_name='mobileid'),
        ),
    ]
