# Generated by Django 4.1.13 on 2024-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_product_order_books_id_order_clothes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=255, null=True, verbose_name='customer'),
        ),
    ]
