# Generated by Django 4.1.13 on 2024-03-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('producer', models.CharField(max_length=255, verbose_name='Producer')),
                ('style', models.CharField(max_length=255, verbose_name='Styles')),
                ('image', models.CharField(max_length=255, verbose_name='Image')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
