# Generated by Django 4.1.13 on 2024-04-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_description_alter_clothes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Image'),
        ),
    ]
