# Generated by Django 4.1.13 on 2024-04-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_clothes_description_alter_clothes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Image'),
        ),
    ]
