# Generated by Django 4.1.13 on 2024-04-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_clothes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='producer',
        ),
    ]
