# Generated by Django 4.1.13 on 2024-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_clothes_id_cart_mobile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(null=True, verbose_name='Total'),
        ),
    ]
