# Generated by Django 4.1.13 on 2024-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='username'),
        ),
    ]
