# Generated by Django 5.0.1 on 2024-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuHouse', models.CharField(max_length=255, verbose_name='nuhHouse')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('district', models.CharField(max_length=255, verbose_name='district')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
            ],
        ),
    ]
