# Generated by Django 4.1.13 on 2024-04-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='publisher',
            field=models.CharField(max_length=255, null=True, verbose_name='Publisher'),
        ),
    ]
