# Generated by Django 4.1.13 on 2024-04-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_mobile_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='producer',
            field=models.CharField(max_length=255, null=True, verbose_name='Producer'),
        ),
    ]
