# Generated by Django 4.1.13 on 2024-04-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('image', models.CharField(max_length=255, verbose_name='Image')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('language', models.CharField(max_length=255, verbose_name='language')),
            ],
        ),
    ]
