# Generated by Django 4.1.13 on 2024-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.FloatField()),
                ('books_id', models.CharField(max_length=255, null=True, verbose_name='bookid')),
                ('mobiles_id', models.CharField(max_length=255, null=True, verbose_name='mobileid')),
                ('clothes_id', models.CharField(max_length=255, null=True, verbose_name='clothesid')),
                ('customer_id', models.CharField(max_length=255, null=True, verbose_name='customerid')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='note')),
                ('method', models.CharField(max_length=255, null=True, verbose_name='method')),
                ('numberphone', models.CharField(max_length=255, null=True, verbose_name='numberphone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='numberphone')),
            ],
        ),
    ]
